# Generated by Django 4.0.6 on 2022-08-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Dictionaries'},
        ),
    ]
