# Generated by Django 4.0.6 on 2022-08-04 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_dictionary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Dictionary'},
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to=settings.AUTH_USER_MODEL),
        ),
    ]
