# Generated by Django 4.0.6 on 2022-08-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dictionary_options_alter_dictionary_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Dictionary'},
        ),
    ]
