# Generated by Django 4.0.6 on 2022-08-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dictionary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ('progress', '-created_at'), 'verbose_name_plural': 'Dictionary'},
        ),
    ]
