# Generated by Django 4.1 on 2022-09-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dictionary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Words sets',
            },
        ),
        migrations.CreateModel(
            name='WordInSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('en_word', models.CharField(max_length=20)),
                ('uk_word', models.CharField(max_length=20)),
                ('words_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.wordsset')),
            ],
            options={
                'verbose_name_plural': 'Words in sets',
                'ordering': ('-created_at',),
                'unique_together': {('en_word', 'uk_word', 'words_set_id')},
            },
        ),
    ]
