version: '3.9'

services:

  db:
    restart: always
    image: postgres
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    restart: always
    container_name: api
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  db:
