version: "3.2"
services:

  db:
    restart: always
    image: postgres
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    restart: always
    command: npm start
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: react
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db:
