name: Deploy
# on:
#   push:
#     branches:
#       - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy WCA
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            docker exec -t postgres pg_dumpall -c -U ${{secrets.DB_NAME}} > /home/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
            git pull origin master
            docker-compose down
            docker-compose up --build -d
            docker image rm $(docker image ls -f 'dangling=true' -q)
            echo "Done"
