name: Deploy
on:
  push:
    branches:
      - git-actions

jobs: 

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy WCA  
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir test
            cd test
            git clone git@github.com:newdisease/words-coach-app.git
            echo "Deployment complete"
